// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0h7EDnMR-yDbFwB6_pd3Djy-8DHdjMbQ',
    appId: '1:16204209836:web:ea840f5a5e4c71b24e4909',
    messagingSenderId: '16204209836',
    projectId: 'ecommerce-6898',
    authDomain: 'ecommerce-6898.firebaseapp.com',
    storageBucket: 'ecommerce-6898.appspot.com',
    measurementId: 'G-P7EEMXRJ3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoukgNOnShjzlwU7BV92eGXLLJlrd-ZfM',
    appId: '1:16204209836:android:f12f7e49e0bbafce4e4909',
    messagingSenderId: '16204209836',
    projectId: 'ecommerce-6898',
    storageBucket: 'ecommerce-6898.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRfOhbK8CMgAONlJ9adfu4-XJHjWDVdI',
    appId: '1:16204209836:ios:007a1e3e408e03fd4e4909',
    messagingSenderId: '16204209836',
    projectId: 'ecommerce-6898',
    storageBucket: 'ecommerce-6898.appspot.com',
    iosClientId: '16204209836-0re9et4k9krf83ej137qfm698bmcdlta.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMRfOhbK8CMgAONlJ9adfu4-XJHjWDVdI',
    appId: '1:16204209836:ios:007a1e3e408e03fd4e4909',
    messagingSenderId: '16204209836',
    projectId: 'ecommerce-6898',
    storageBucket: 'ecommerce-6898.appspot.com',
    iosClientId: '16204209836-0re9et4k9krf83ej137qfm698bmcdlta.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
